schema:
  - https://graphql.datocms.com:
      headers:
        Authorization: 'Bearer 25c0023baa57996205b6782f4003dc'
        X-Exclude-Invalid: true
documents: './lib/dato/**/*.graphql'
generates:
  generated/dato.ts:
    plugins:
      - typescript
      - typescript-operations:
          strictScalars: true
          scalars:
            BooleanType: boolean
            CustomData: Record<string, unknown>
            Date: string
            DateTime: string
            FloatType: number
            IntType: number
            ItemId: string
            JsonField: unknown
            MetaTagAttributes: Record<string, string>
            UploadId: string
      - typed-document-node
